DROP TABLE BOARD;

CREATE TABLE BOARD (
UNQ NUMBER PRIMARY KEY NOT NULL, 
TITLE VARCHAR2(100 BYTE) NOT NULL, 
CONTENT VARCHAR2(4000 BYTE), 
HITS NUMBER DEFAULT '0', 
RDATE TIMESTAMP , 
UDATE TIMESTAMP 
);

CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1;